version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c " python scripts/comment_apps.py
      && python manage.py migrate
      && python scripts/uncomment_apps.py
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vibestocks
      - POSTGRES_PASSWORD=vibestocks
      - POSTGRES_DB=vibestocks

volumes:
  postgres_data:
