# Generated by Django 4.2.11 on 2024-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_alert_activated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alert_activated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='days_since_alert_activated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='days_to_activate_alert',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('USABLE', 'Usable'), ('TO_EXPIRE', 'To Expire'), ('EXPIRED', 'Expired')], default='USABLE'),
        ),
    ]
