# Generated by Django 4.2.11 on 2024-04-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_alert_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='days_to_expire',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='expired_days',
            field=models.SmallIntegerField(default=0),
        ),
    ]
