# Generated by Django 4.2.11 on 2024-04-09 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_product_days_to_expire_product_expired_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpirationAlerts',
            new_name='ExpirationAlert',
        ),
    ]
