# Generated by Django 4.2.11 on 2024-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_expirationalerts_expirationalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('USABLE', 'Usable'), ('TO_EXPIRE', 'To Expire'), ('EXPIRED', 'Expired')], default='USABLE', max_length=16),
        ),
    ]
